# This is a markdown file exploring and cleaning UNICEF Data.  This is just to get a feel for the data and to see how they compare across resources.  We may find that the data is basically the same, which is highly possible.

In [114]:
import pandas as pd
import data_cleaner as clean

## Load the data

In [115]:
fertility = pd.read_csv("../data/UNICEF-FERTILITY-RATE-2018.csv ")  
pregnant_women_dr_visits2018_4x = pd.read_csv("../data/UNICEF-PREGNANT-WOMEN-WHO-VISIT-DOCTOR-AT-LEAST-FOUR-TIMES-%UNIT-2018.csv")
imr2018 = pd.read_csv("../data/UNICEF-IMR-2018.csv")
pregnant_women_dr_visits2018_1x = pd.read_csv("../data/UNICEF-PREGNANT-WOMEN-WHO-VISIT-DOCTOR-AT-LEAST-ONCE-%UNIT-2018.csv")
infant_death2018 = pd.read_csv("../data/UNICEF-INFANT-DEATH-2018.csv")
low_birth_wt2015 = pd.read_csv("../data/UNICEF-PREVALENCE-OF-LOW-BIRTH-WEIGHT-2015.csv")
links = pd.read_excel("../data/UNICEF-LINKS.xlsx")
vaccine_coverage2018 = pd.read_csv("../data/UNICEF-VACCINE-COVERAGE-BY-ANTIGEN-2018.csv")
maternal_death2017 = pd.read_csv("../data/UNICEF-MATERNAL-DEATH-2017.csv")
unicef_who_joint_immun_report2016 = pd.read_excel("../data/UNICEF-WHO-IMMUNIZATION-JOINT-REPORT-2016.xls")
births2018 = pd.read_csv("../data/UNICEF-NUMBER-OF-BIRTH-2018.csv")

In [116]:
reports = [
    unicef_who_joint_immun_report2016,
    links
]

datasets = [
    fertility, 
    pregnant_women_dr_visits2018_4x, 
    pregnant_women_dr_visits2018_1x, 
    imr2018, 
    infant_death2018, 
    low_birth_wt2015,
    vaccine_coverage2018,
    maternal_death2017,
    births2018
]

## Step 1: Examine and clean each dataset

### Data Cleaning first pass
Remove empty columns in each dataset and split 'REF_AREA:Geographic area' and 'INDICATOR:Indicator'

In [117]:
cols_to_split = ['INDICATOR:Indicator', 'REF_AREA:Geographic area']
for df in datasets:
    df.dropna(how="all", axis=1, inplace=True)
    for col in cols_to_split:
        if col in df.columns:
            clean.split_cols(df, col)

### Step 1a: Fertility

In [118]:
fertility.columns

Index(['DATAFLOW', 'SEX:Sex', 'TIME_PERIOD:Time period',
       'OBS_VALUE:Observation Value', 'UNIT_MULTIPLIER:Unit multiplier',
       'UNIT_MEASURE:Unit of measure', 'DATA_SOURCE:Data Source', 'INDICATOR',
       'Indicator', 'REF_AREA', 'Geographic area'],
      dtype='object')

In [119]:
fertility.head()

,DATAFLOW,SEX:Sex,TIME_PERIOD:Time period,OBS_VALUE:Observation Value,UNIT_MULTIPLIER:Unit multiplier,UNIT_MEASURE:Unit of measure,DATA_SOURCE:Data Source,INDICATOR,Indicator,REF_AREA,Geographic area
0,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,_T: Total,2018,4.473,0: Units,PCNT: %,UNPD2019,DM_FRATE_TOT,Total fertility rate,AFG,Afghanistan
1,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,_T: Total,2018,1.617,0: Units,PCNT: %,UNPD2019,DM_FRATE_TOT,Total fertility rate,ALB,Albania
2,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,_T: Total,2018,3.023,0: Units,PCNT: %,UNPD2019,DM_FRATE_TOT,Total fertility rate,DZA,Algeria
3,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,_T: Total,2018,NaN,0: Units,PCNT: %,UNPD2019,DM_FRATE_TOT,Total fertility rate,AND,Andorra
4,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,_T: Total,2018,5.519,0: Units,PCNT: %,UNPD2019,DM_FRATE_TOT,Total fertility rate,AGO,Angola

In [120]:
relevant_cols = [
    'DATAFLOW', 'INDICATOR:Indicator', 'SEX:Sex', 'TIME_PERIOD:Time period',
       'OBS_VALUE:Observation Value', 'UNIT_MULTIPLIER:Unit multiplier',
       'UNIT_MEASURE:Unit of measure', 'DATA_SOURCE:Data Source', 'REF_AREA',
       'Geographic area'
]

In [110]:
combined_df = pd.DataFrame()

In [112]:
##Start combining dataframes here:

Index([], dtype='object')

In [107]:
imr2018.head()

,DATAFLOW,INDICATOR:Indicator,SEX:Sex,TIME_PERIOD:Time period,OBS_VALUE:Observation Value,UNIT_MEASURE:Unit of measure,OBS_STATUS:Observation Status,LOWER_BOUND:Lower Bound,UPPER_BOUND:Upper Bound,OBS_FOOTNOTE:Observation footnote,AGE:Current age,REF_AREA,Geographic area
0,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,CME_MRY0: Infant mortality rate,F: Female,2018,44.559440,D_PER_1000_B: Deaths per 1000 live births,A: Normal value,36.876155,52.432606,NaN,_T: Total,AFG,Afghanistan
1,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,CME_MRY0: Infant mortality rate,M: Male,2018,51.347098,D_PER_1000_B: Deaths per 1000 live births,A: Normal value,42.559612,60.399456,NaN,_T: Total,AFG,Afghanistan
2,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,CME_MRY0: Infant mortality rate,_T: Total,2018,48.043335,D_PER_1000_B: Deaths per 1000 live births,A: Normal value,39.944302,56.320057,NaN,_T: Total,AFG,Afghanistan
3,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,CME_MRY0: Infant mortality rate,F: Female,2018,7.551900,D_PER_1000_B: Deaths per 1000 live births,A: Normal value,7.129561,7.995427,NaN,_T: Total,ALB,Albania
4,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,CME_MRY0: Infant mortality rate,M: Male,2018,9.340910,D_PER_1000_B: Deaths per 1000 live births,A: Normal value,8.850254,9.885789,NaN,_T: Total,ALB,Albania

In [13]:
imr2018.columns

Index(['DATAFLOW', 'REF_AREA:Geographic area', 'INDICATOR:Indicator',
       'SEX:Sex', 'TIME_PERIOD:Time period', 'OBS_VALUE:Observation Value',
       'UNIT_MULTIPLIER:Unit multiplier', 'UNIT_MEASURE:Unit of measure',
       'OBS_STATUS:Observation Status', 'OBS_CONF:Observation confidentaility',
       'LOWER_BOUND:Lower Bound', 'UPPER_BOUND:Upper Bound',
       'WGTD_SAMPL_SIZE:Weighted Sample Size',
       'OBS_FOOTNOTE:Observation footnote', 'SERIES_FOOTNOTE:Series footnote',
       'DATA_SOURCE:Data Source',
       'SOURCE_LINK:Citation of or link to the data source',
       'CUSTODIAN:Custodian',
       'TIME_PERIOD_METHOD:Time period activity related to when the data are collected',
       'REF_PERIOD:Reference Period',
       'COVERAGE_TIME:The period of time for which data are provided',
       'AGE:Current age'],
      dtype='object')

In [18]:
to_remove = [
    'AGE:Current age', #All the same
    'OBS_STATUS:Observation Status', #All the same
    'WGTD_SAMPL_SIZE:Weighted Sample Size',
    'OBS_FOOTNOTE:Observation footnote',
    'SERIES_FOOTNOTE:Series footnote',
]

to_split = [
    'REF_AREA:Geographic area'
]

imr2018_clean = clean.clean_data(imr2018, to_remove, to_split)

Columns split:

Original Column: REF_AREA:Geographic area

Split columns: ['REF_AREA', 'Geographic area']

Relevant columns: ['REF_AREA', 'Geographic area', 'DATAFLOW', 'INDICATOR:Indicator', 'SEX:Sex', 'TIME_PERIOD:Time period', 'OBS_VALUE:Observation Value', 'UNIT_MEASURE:Unit of measure', 'LOWER_BOUND:Lower Bound', 'UPPER_BOUND:Upper Bound']

Columns removed: ['AGE:Current age', 'OBS_STATUS:Observation Status', 'WGTD_SAMPL_SIZE:Weighted Sample Size', 'OBS_FOOTNOTE:Observation footnote', 'SERIES_FOOTNOTE:Series footnote', 'REF_AREA:Geographic area', 'REF_AREA:Geographic area', 'UNIT_MULTIPLIER:Unit multiplier', 'OBS_STATUS:Observation Status', 'OBS_CONF:Observation confidentaility', 'WGTD_SAMPL_SIZE:Weighted Sample Size', 'OBS_FOOTNOTE:Observation footnote', 'SERIES_FOOTNOTE:Series footnote', 'DATA_SOURCE:Data Source', 'SOURCE_LINK:Citation of or link to the data source', 'CUSTODIAN:Custodian', 'TIME_PERIOD_METHOD:Time period activity related to when the data are collected', 'REF_PERIOD:Reference Period', 'COVERAGE_TIME:The period of time for which data are provided', 'AGE:Current age']

In [19]:
imr2018_clean.head()

,REF_AREA,Geographic area,DATAFLOW,INDICATOR:Indicator,SEX:Sex,TIME_PERIOD:Time period,OBS_VALUE:Observation Value,UNIT_MEASURE:Unit of measure,LOWER_BOUND:Lower Bound,UPPER_BOUND:Upper Bound
0,AFG,Afghanistan,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,CME_MRY0: Infant mortality rate,F: Female,2018,44.559440,D_PER_1000_B: Deaths per 1000 live births,36.876155,52.432606
1,AFG,Afghanistan,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,CME_MRY0: Infant mortality rate,M: Male,2018,51.347098,D_PER_1000_B: Deaths per 1000 live births,42.559612,60.399456
2,AFG,Afghanistan,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,CME_MRY0: Infant mortality rate,_T: Total,2018,48.043335,D_PER_1000_B: Deaths per 1000 live births,39.944302,56.320057
3,ALB,Albania,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,CME_MRY0: Infant mortality rate,F: Female,2018,7.551900,D_PER_1000_B: Deaths per 1000 live births,7.129561,7.995427
4,ALB,Albania,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,CME_MRY0: Infant mortality rate,M: Male,2018,9.340910,D_PER_1000_B: Deaths per 1000 live births,8.850254,9.885789

## The data and column names in UNICEF are much more specific, which is good and bad.  We're going to reformat some of it to make it easier to join data, and we will only look at columns we find relevant for the analysis to make it easier to work with (**COME BACK TO THIS ONCE ALL THE TABLES ARE JOINED, IT'LL BE EASIER TO DO IT ONCE INSTEAD OF 4 TIMES**)

### Step 1b: Infant Death

In [9]:
unicef_infant_death.head()

,DATAFLOW,REF_AREA:Geographic area,INDICATOR:Indicator,SEX:Sex,TIME_PERIOD:Time period,OBS_VALUE:Observation Value,UNIT_MULTIPLIER:Unit multiplier,UNIT_MEASURE:Unit of measure,OBS_STATUS:Observation Status,OBS_CONF:Observation confidentaility,...,WGTD_SAMPL_SIZE:Weighted Sample Size,OBS_FOOTNOTE:Observation footnote,SERIES_FOOTNOTE:Series footnote,DATA_SOURCE:Data Source,SOURCE_LINK:Citation of or link to the data source,CUSTODIAN:Custodian,TIME_PERIOD_METHOD:Time period activity related to when the data are collected,REF_PERIOD:Reference Period,COVERAGE_TIME:The period of time for which data are provided,AGE:Current age
0,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,AFG: Afghanistan,CME_TMY0: Infant deaths,F: Female,2018,25852,NaN,D: Number of deaths,A: Normal value,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,_T: Total
1,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,AFG: Afghanistan,CME_TMY0: Infant deaths,M: Male,2018,31542,NaN,D: Number of deaths,A: Normal value,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,_T: Total
2,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,AFG: Afghanistan,CME_TMY0: Infant deaths,_T: Total,2018,57394,NaN,D: Number of deaths,A: Normal value,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,_T: Total
3,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,ALB: Albania,CME_TMY0: Infant deaths,F: Female,2018,124,NaN,D: Number of deaths,A: Normal value,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,_T: Total
4,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,ALB: Albania,CME_TMY0: Infant deaths,M: Male,2018,165,NaN,D: Number of deaths,A: Normal value,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,_T: Total

In [10]:
unicef_infant_death.describe()

,TIME_PERIOD:Time period,OBS_VALUE:Observation Value,UNIT_MULTIPLIER:Unit multiplier,OBS_CONF:Observation confidentaility,LOWER_BOUND:Lower Bound,UPPER_BOUND:Upper Bound,WGTD_SAMPL_SIZE:Weighted Sample Size,OBS_FOOTNOTE:Observation footnote,SERIES_FOOTNOTE:Series footnote,DATA_SOURCE:Data Source,SOURCE_LINK:Citation of or link to the data source,CUSTODIAN:Custodian,TIME_PERIOD_METHOD:Time period activity related to when the data are collected,REF_PERIOD:Reference Period,COVERAGE_TIME:The period of time for which data are provided
count,693.0,6.930000e+02,0.0,0.0,6.930000e+02,6.930000e+02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2018.0,7.548683e+04,NaN,NaN,6.995821e+04,8.294032e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.0,2.911086e+05,NaN,NaN,2.769288e+05,3.117107e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2018.0,0.000000e+00,NaN,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2018.0,1.760000e+02,NaN,NaN,1.500000e+02,2.150000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2018.0,2.095000e+03,NaN,NaN,1.631000e+03,2.698000e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2018.0,2.085600e+04,NaN,NaN,1.574300e+04,2.438500e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2018.0,4.010099e+06,NaN,NaN,3.880481e+06,4.215378e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
unicef_infant_death.columns

Index(['DATAFLOW', 'REF_AREA:Geographic area', 'INDICATOR:Indicator',
       'SEX:Sex', 'TIME_PERIOD:Time period', 'OBS_VALUE:Observation Value',
       'UNIT_MULTIPLIER:Unit multiplier', 'UNIT_MEASURE:Unit of measure',
       'OBS_STATUS:Observation Status', 'OBS_CONF:Observation confidentaility',
       'LOWER_BOUND:Lower Bound', 'UPPER_BOUND:Upper Bound',
       'WGTD_SAMPL_SIZE:Weighted Sample Size',
       'OBS_FOOTNOTE:Observation footnote', 'SERIES_FOOTNOTE:Series footnote',
       'DATA_SOURCE:Data Source',
       'SOURCE_LINK:Citation of or link to the data source',
       'CUSTODIAN:Custodian',
       'TIME_PERIOD_METHOD:Time period activity related to when the data are collected',
       'REF_PERIOD:Reference Period',
       'COVERAGE_TIME:The period of time for which data are provided',
       'AGE:Current age'],
      dtype='object')

### Step 1c: Birth

In [12]:
unicef_birth.head()

,Geographic area,Indicator,Sex,TIME_PERIOD,OBS_VALUE,Unit multiplier,Unit of measure,Observation Status,Observation confidentaility,LOWER_BOUND,...,WGTD_SAMPL_SIZE,OBS_FOOTNOTE,SERIES_FOOTNOTE,DATA_SOURCE,SOURCE_LINK,CUSTODIAN,Time period activity related to when the data are collected,REF_PERIOD,COVERAGE_TIME,Current age
0,Afghanistan,Number of births,Total,2018,1206.951,Thousands,Persons,NaN,NaN,NaN,...,NaN,NaN,NaN,UNPD2019,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,Number of births,Total,2018,33.931,Thousands,Persons,NaN,NaN,NaN,...,NaN,NaN,NaN,UNPD2019,NaN,NaN,NaN,NaN,NaN,NaN
2,Algeria,Number of births,Total,2018,1023.275,Thousands,Persons,NaN,NaN,NaN,...,NaN,NaN,NaN,UNPD2019,NaN,NaN,NaN,NaN,NaN,NaN
3,Andorra,Number of births,Total,2018,NaN,Thousands,Persons,NaN,NaN,NaN,...,NaN,NaN,NaN,UNPD2019,NaN,NaN,NaN,NaN,NaN,NaN
4,Angola,Number of births,Total,2018,1257.284,Thousands,Persons,NaN,NaN,NaN,...,NaN,NaN,NaN,UNPD2019,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
unicef_birth.describe()

,TIME_PERIOD,OBS_VALUE,Observation Status,Observation confidentaility,LOWER_BOUND,UPPER_BOUND,WGTD_SAMPL_SIZE,OBS_FOOTNOTE,SERIES_FOOTNOTE,SOURCE_LINK,CUSTODIAN,Time period activity related to when the data are collected,REF_PERIOD,COVERAGE_TIME,Current age
count,202.0,184.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2018.0,759.858902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.0,2335.010181,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2018.0,1.475000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2018.0,46.314000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2018.0,166.243000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2018.0,635.255750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2018.0,24164.357000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
unicef_birth.columns

Index(['Geographic area', 'Indicator', 'Sex', 'TIME_PERIOD', 'OBS_VALUE',
       'Unit multiplier', 'Unit of measure', 'Observation Status',
       'Observation confidentaility', 'LOWER_BOUND', 'UPPER_BOUND',
       'WGTD_SAMPL_SIZE', 'OBS_FOOTNOTE', 'SERIES_FOOTNOTE', 'DATA_SOURCE',
       'SOURCE_LINK', 'CUSTODIAN',
       'Time period activity related to when the data are collected',
       'REF_PERIOD', 'COVERAGE_TIME', 'Current age'],
      dtype='object')

### Step 1d: Vaccine Coverage

In [15]:
unicef_vaccine_coverage.head()

,DATAFLOW,REF_AREA:Geographic area,INDICATOR:Indicator,SEX:Sex,TIME_PERIOD:Time period,OBS_VALUE:Observation Value,UNIT_MULTIPLIER:Unit multiplier,UNIT_MEASURE:Unit of measure,OBS_STATUS:Observation Status,OBS_CONF:Observation confidentaility,...,WGTD_SAMPL_SIZE:Weighted Sample Size,OBS_FOOTNOTE:Observation footnote,SERIES_FOOTNOTE:Series footnote,DATA_SOURCE:Data Source,SOURCE_LINK:Citation of or link to the data source,CUSTODIAN:Custodian,TIME_PERIOD_METHOD:Time period activity related to when the data are collected,REF_PERIOD:Reference Period,COVERAGE_TIME:The period of time for which data are provided,AGE:Current age
0,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,AFG: Afghanistan,IM_DTP1: Percentage of surviving infants who r...,_T: Total,2018,73,0: Units,PCNT: %,E: Estimated value,F: Free,...,NaN,NaN,NaN,WHO/UNICEF estimates of national immunization ...,NaN,NaN,NaN,NaN,NaN,M12T23: 12 to 23 months old
1,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,AFG: Afghanistan,IM_DTP3: Percentage of surviving infants who r...,_T: Total,2018,66,0: Units,PCNT: %,E: Estimated value,F: Free,...,NaN,NaN,NaN,WHO/UNICEF estimates of national immunization ...,NaN,NaN,NaN,NaN,NaN,M12T23: 12 to 23 months old
2,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,AFG: Afghanistan,IM_MCV1: Percentage of surviving infants who r...,_T: Total,2018,64,0: Units,PCNT: %,E: Estimated value,F: Free,...,NaN,NaN,NaN,WHO/UNICEF estimates of national immunization ...,NaN,NaN,NaN,NaN,NaN,M12T23: 12 to 23 months old
3,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,AFG: Afghanistan,IM_POL3: Percentage of surviving infants who r...,_T: Total,2018,73,0: Units,PCNT: %,E: Estimated value,F: Free,...,NaN,NaN,NaN,WHO/UNICEF estimates of national immunization ...,NaN,NaN,NaN,NaN,NaN,M12T23: 12 to 23 months old
4,UNICEF:GLOBAL_DATAFLOW(1.0): Cross-sector indi...,AFG: Afghanistan,IM_BCG: Percentage of live births who received...,_T: Total,2018,78,0: Units,PCNT: %,E: Estimated value,F: Free,...,NaN,NaN,NaN,WHO/UNICEF estimates of national immunization ...,NaN,NaN,NaN,NaN,NaN,Y0: Under 1 year old

In [16]:
unicef_vaccine_coverage.describe()

,TIME_PERIOD:Time period,OBS_VALUE:Observation Value,LOWER_BOUND:Lower Bound,UPPER_BOUND:Upper Bound,WGTD_SAMPL_SIZE:Weighted Sample Size,SERIES_FOOTNOTE:Series footnote,SOURCE_LINK:Citation of or link to the data source,CUSTODIAN:Custodian,TIME_PERIOD_METHOD:Time period activity related to when the data are collected,REF_PERIOD:Reference Period,COVERAGE_TIME:The period of time for which data are provided
count,2410.0,2410.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2018.0,84.536515,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,0.0,17.850578,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,2018.0,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,2018.0,80.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2018.0,91.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,2018.0,97.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,2018.0,99.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
unicef_vaccine_coverage.columns

Index(['DATAFLOW', 'REF_AREA:Geographic area', 'INDICATOR:Indicator',
       'SEX:Sex', 'TIME_PERIOD:Time period', 'OBS_VALUE:Observation Value',
       'UNIT_MULTIPLIER:Unit multiplier', 'UNIT_MEASURE:Unit of measure',
       'OBS_STATUS:Observation Status', 'OBS_CONF:Observation confidentaility',
       'LOWER_BOUND:Lower Bound', 'UPPER_BOUND:Upper Bound',
       'WGTD_SAMPL_SIZE:Weighted Sample Size',
       'OBS_FOOTNOTE:Observation footnote', 'SERIES_FOOTNOTE:Series footnote',
       'DATA_SOURCE:Data Source',
       'SOURCE_LINK:Citation of or link to the data source',
       'CUSTODIAN:Custodian',
       'TIME_PERIOD_METHOD:Time period activity related to when the data are collected',
       'REF_PERIOD:Reference Period',
       'COVERAGE_TIME:The period of time for which data are provided',
       'AGE:Current age'],
      dtype='object')